spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
spring.datasource.username=root
spring.datasource.password=Pard&$86
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#===========================================================
# Security User Configuration
#===========================================================

# ADMIN User- can access everything including POST/DELETE
  spring.security.user.name=ADMIN
  spring.security.user.password=Pardon123
  spring.security.user.roles=ADMIN


